version: '3'
services:
  postgresql:
    image: postgres:9.6.10-alpine
    environment:
      POSTGRES_PASSWORD: snello
      POSTGRES_USER: snello
      POSTGRES_DB: snello
    ports:
      - '5432:5432'
  pgadmin4:
    image: fenglc/pgadmin4
    ports:
      - '5050:5050'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
  snello-api:
    restart: always
    image: snellocms/snello-api:local
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      JDBC_HOST: postgresql
      JDBC_TYPE: postgresql
      JDBC_PORT: 5432
      JDBC_DB: snello
      JDBC_USERNAME: snello
      JDBC_PASSWORD: snello
      JDBC_DRIVER: org.postgresql.Driver
      MICRONAUT_DB_TYPE: postgresql
      WEB_PATH: "/home/snello/files/"
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787"
      TZ: "Europe/Rome"
