version: '3'
services:
  mysql:
    image: mysql:8.0.17
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: snello
      MYSQL_DATABASE: snello
      MYSQL_USER: snello
      MYSQL_PASSWORD: snello
    command: [--character-set-server=utf8mb4,--max-connections=1000, --wait-timeout=300, --interactive-timeout=300, --collation-server=utf8mb4_unicode_ci,--default-authentication-plugin=mysql_native_password]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge-4.9
    logging:
      driver: none
    depends_on:
      - mysql
    links:
      - mysql:db
    expose:
      - "9999"
    ports:
      - "9999:80"
