---
micronaut:
  application:
    name: snello-api

  server:
    cors:
      enabled: true
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: /static/**
        paths:
          - file:${WEBROOT:`/home/snello/webroot`}
endpoints:
  health:
    enabled: true
#  metrics:
#    enabled: true
#    export:
#      prometheus:
#        enabled: true
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
  dateFormat: yyyy-MM-dd HH:mm:ss
---
datasources:
  default:
    url:  ${JDBC_URL:`jdbc:mysql://mysql:3306/snello?verifyServerCertificate=false&useSSL=true`}
    username: ${JDBC_USERNAME:snello}
    password: ${JDBC_PASSWORD:snello}
    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
    testOnBorrow: true
    validationQuery: ${JDBC_VALIDATION_QUERY:'select 1'}
    removeAbandoned: true
    removeAbandonedOnBorrow: true
    removeAbandonedOnMaintenance: true

