---
micronaut:
  application:
    name: snellocms
  server:
    cors:
      enabled: true
      configurations:
        all:
          exposedHeaders:
            - Authorization
            - authorization
            - Origin
            - origin
            - X-Requested-With
            - x-request-with
            - Content-Type
            - content-type
            - Accept
            - accept
            - X-total-count
            - x-total-count
            - size
            - Size
    port: 8080
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths:
          - file:${web.path:"/home/snello/public"}
      files:
        enabled: true
        mapping: /files/**
        paths:
          - file:${web.files.path:"/home/snello/public/files"}
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${jwt.generator.signature.secret:pleaseChangeThisSecretForANewOne}"
  storage:
    type: fs
  db:
    type: postgresql
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
  dateFormat: yyyy-MM-dd HH:mm:ss
---
datasources:
  default:
    url:  jdbc:${JDBC_TYPE:postgresql}://${JDBC_HOST:localhost}:${JDBC_PORT:5432}/${JDBC_DB:snello}
    username: ${JDBC_USERNAME:snello}
    password: ${JDBC_PASSWORD:snello}
    database: ${JDBC_DB:snello}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    maxActive: ${JDBC_MAX_ACTIVE:100}
    initialSize: ${JDBC_INITIAL_SIZE:10}
    testOnBorrow: true
    validationQuery: select 1
    removeAbandoned: true
    removeAbandonedOnBorrow: true
    removeAbandonedOnMaintenance: true
