---
micronaut:
  application:
    name: snello-api
  server:
    cors:
      enabled: true
      configurations:
        all:
          exposedHeaders:
            - Authorization
            - authorization
            - Origin
            - origin
            - X-Requested-With
            - x-request-with
            - Content-Type
            - content-type
            - Accept
            - accept
            - X-total-count
            - x-total-count
            - size
            - Size
    port: 8080
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB
  router:
    static-resources:
      default:
        enabled: true
        mapping: /files/**
        paths:
          - file:${WEB_PATH:"/Users/fiorenzo/IdeaProjectsSnello/matcms/docker/webapp/files/"}
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
  storage:
    type: ${STORAGE_TYPE:fs}
  db:
    type: ${DB_TYPE:mysql}
  s3:
    endpoint:  ${S3_ENDPOINT:s3.amazonaws.com}
    accesskey: ${S3_ACCESS_KEY:xxxxxxxxx}
    secretkey: ${S3_SECRET_KEY:xxxxxxxxx}
    region: ${S3_REGION:eu-central-1}
    bucketname: ${S3_BUCKETNAME:xxxxxxxxx}
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
  dateFormat: yyyy-MM-dd HH:mm:ss
---
datasources:
  default:
    url:  jdbc:mysql://${JDBC_HOST:localhost}:${JDBC_PORT:3306}/${JDBC_DB:matcms}?verifyServerCertificate=false&useSSL=${JDBC_USE_SSL:false}
    username: ${JDBC_USERNAME:matcms}
    password: ${JDBC_PASSWORD:matcms}
    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
    testOnBorrow: true
    validationQuery: select 1
    removeAbandoned: true
    removeAbandonedOnBorrow: true
    removeAbandonedOnMaintenance: true
