---
micronaut:
  application:
    name: matcms

  server:
    cors:
      enabled: true
    port: 8080
  router:
    static-resources:
      default:
        enabled: true
        mapping: /files/**
        paths:
          - file:files/
endpoints:
  health:
    enabled: true
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
---
jackson:
  serialization:
    writeDatesAsTimestamps: false
  dateFormat: yyyy-MM-dd HH:mm:ss
---
datasources:
  default:
    url: jdbc:mysql://localhost:3307/snello?verifyServerCertificate=false&useSSL=true
    username: snello
    password: snello
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: select 1
    removeAbandoned: true
    removeAbandonedOnBorrow: true
    removeAbandonedOnMaintenance: true

