---
micronaut:
  application:
    name: snello-api
  storage:
    type: s3
  s3:
    endpoint: ${S3_ENDPOINT:s3.amazonaws.com}
    accesskey: ${S3_ACCESSKEY:s3.amazonaws.com}
    secretkey: ${S3_SECRETKEY:secretkey}
    region: ${S3_REGION:eu-central-1}
    bucketname: ${S3_BUCKETNAME:matcms}
