version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: matcms
      MYSQL_DATABASE: matcms
      MYSQL_USER: matcms
      MYSQL_PASSWORD: matcms
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --max-connections=1000, --wait-timeout=300, --interactive-timeout=300]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    logging:
      driver: none
    depends_on:
      - mysql
    links:
      - mysql:db
    expose:
      - "9999"
    ports:
      - "9999:80"